# Generated from «Насадки на оружие — на согласование.docx».
ATTACHMENTS = [{'name': 'Траншейный прицел',
  'slot': 'Прицел',
  'kinds': 'Все',
  'price': 5,
  'access': 'Снабжение I',
  'effect': 'Кубы Стрельбы +1',
  'skill': 1},
 {'name': 'Ремень для быстрого хвата',
  'slot': 'Опора',
  'kinds': 'Все',
  'price': 5,
  'access': 'Снабжение I',
  'effect': 'Экипировка и снятие оружия не требуют манёвра.'},
 {'name': 'Увеличенный магазин пистолета',
  'slot': 'Магазин',
  'kinds': 'Пистолет',
  'price': 10,
  'access': 'Снабжение II',
  'effect': 'БК +2\n+2 к боезапасу.',
  'ammo': 2},
 {'name': 'Барабанный магазин пистолета',
  'slot': 'Магазин',
  'kinds': 'Пистолет',
  'price': 20,
  'access': 'Снабжение III',
  'effect': 'БК +5; Руки +1',
  'ammo': 5,
  'hands': 1},
 {'name': 'Длинный пистолетный ствол',
  'slot': 'Ствол',
  'kinds': 'Пистолет',
  'price': 16,
  'access': 'Снабжение II',
  'effect': 'Дистанция +1',
  'range': 1},
 {'name': 'Ускоренный пистолетный затвор',
  'slot': 'Механизм',
  'kinds': 'Пистолет',
  'price': 14,
  'access': 'Снабжение III',
  'effect': 'СКР +1',
  'fire_rate': 1},
 {'name': 'Винтовочный коробчатый магазин',
  'slot': 'Магазин',
  'kinds': 'Винтовка',
  'price': 15,
  'access': 'Снабжение II',
  'effect': 'БК +4',
  'ammo': 4},
 {'name': 'Тяжёлый винтовочный ствол',
  'slot': 'Ствол',
  'kinds': 'Винтовка',
  'price': 16,
  'access': 'Снабжение IV',
  'effect': 'Урон +1; СКР -1 (минимум 1).',
  'damage': 1,
  'fire_rate': -1},
 {'name': 'Щёчный упор с ремнём',
  'slot': 'Опора',
  'kinds': 'Винтовка',
  'price': 10,
  'access': 'Снабжение II',
  'effect': 'Кубы Стрельбы +1',
  'skill': 1},
 {'name': 'Самозарядный винтовочный блок',
  'slot': 'Механизм',
  'kinds': 'Винтовка',
  'price': 15,
  'access': 'Снабжение IV',
  'effect': 'СКР +1; Качество -1',
  'fire_rate': 1,
  'gear': -1},
 {'name': 'Удлинитель трубчатого магазина',
  'slot': 'Магазин',
  'kinds': 'Дробовик',
  'price': 8,
  'access': 'Снабжение II',
  'effect': 'БК +2',
  'ammo': 2},
 {'name': 'Сужающий чок',
  'slot': 'Ствол',
  'kinds': 'Дробовик',
  'price': 9,
  'access': 'Снабжение III',
  'effect': 'Дистанция +1',
  'range': 1},
 {'name': 'Раструб',
  'slot': 'Ствол',
  'kinds': 'Дробовик',
  'price': 9,
  'access': 'Снабжение III',
  'effect': 'Кубы Стрельбы +2; Дистанция -1',
  'skill': 2,
  'range': -1},
 {'name': 'Усиленная помпа',
  'slot': 'Механизм',
  'kinds': 'Дробовик',
  'price': 11,
  'access': 'Снабжение III',
  'effect': 'СКР +1',
  'fire_rate': 1},
 {'name': 'Ленточный короб увеличенной ёмкости',
  'slot': 'Магазин',
  'kinds': 'Пулемёт',
  'price': 20,
  'access': 'Снабжение IV',
  'effect': 'БК +8; Руки +1',
  'ammo': 8,
  'hands': 1},
 {'name': 'Сошки пулемётчика',
  'slot': 'Опора',
  'kinds': 'Пулемёт',
  'price': 15,
  'access': 'Снабжение III',
  'effect': 'Кубы Стрельбы +2.',
  'skill': 2},
 {'name': 'Водяной кожух ствола',
  'slot': 'Ствол',
  'kinds': 'Пулемёт',
  'price': 20,
  'access': 'Снабжение IV',
  'effect': 'СКР +2; Руки +1',
  'fire_rate': 2,
  'hands': 1},
 {'name': 'Облегчённый пулемётный затвор',
  'slot': 'Механизм',
  'kinds': 'Пулемёт',
  'price': 18,
  'access': 'Снабжение V',
  'effect': 'СКР +2; Качество -2',
  'fire_rate': 2,
  'gear': -2},
 {'name': 'Оптический прицел ×2',
  'slot': 'Прицел',
  'kinds': 'Винтовка,Пулемёт',
  'price': 16,
  'access': 'Снабжение II',
  'effect': 'Кубы Стрельбы +2',
  'skill': 2},
 {'name': 'Складной штык',
  'slot': 'Ствол',
  'kinds': 'Винтовка,Дробовик',
  'price': 6,
  'access': 'Снабжение I',
  'effect': 'Урон в Драке +1\nПозволяет использовать оружие в Драке.',
  'melee_damage': 1},
 {'name': 'Пламегаситель',
  'slot': 'Ствол',
  'kinds': 'Пистолет,Винтовка,Пулемёт',
  'price': 15,
  'access': 'Снабжение II',
  'effect': 'Урон +1, дистанция -1',
  'damage': 1,
  'range': -1},
 {'name': 'Утяжелённая рукоять',
  'slot': 'Рукоять',
  'kinds': 'Пистолет,Винтовка,Дробовик',
  'price': 5,
  'access': 'Снабжение I',
  'effect': 'Кубы Стрельбы +1',
  'skill': 1}]

ATTACHMENT_BY_NAME = {item["name"]: item for item in ATTACHMENTS}
RANGE_ORDER = ("Нулевая", "Ближняя", "Средняя", "Дальняя")

def weapon_kind(item):
    name = str(item.get("name") or "").casefold()
    text = str(item.get("conditions") or "").casefold()
    if int(item.get("fire_rate") or 0) >= 4 or "пулемёт" in name:
        return "Пулемёт"
    if "дроб" in name or "ружь" in name or "боеприпас: д" in text:
        return "Дробовик"
    if "пистолет" in name or "револьвер" in name or "ракетниц" in name or "боеприпас: п" in text:
        return "Пистолет"
    return "Винтовка"

def compatible(spec, weapon):
    kinds = {part.strip() for part in spec["kinds"].split(",")}
    return "Все" in kinds or weapon_kind(weapon) in kinds

def apply_attachments(weapon, specs):
    result = dict(weapon)
    result["attachments"] = [spec["name"] for spec in specs]
    result["attachment_skill_bonus"] = sum(int(spec.get("skill") or 0) for spec in specs)
    result["damage"] = max(0, int(result.get("damage") or 0) + sum(int(spec.get("damage") or 0) for spec in specs))
    result["fire_rate"] = max(1, int(result.get("fire_rate") or 1) + sum(int(spec.get("fire_rate") or 0) for spec in specs))
    if result.get("ammo_max") is not None:
        result["ammo_max"] = max(1, int(result["ammo_max"]) + sum(int(spec.get("ammo") or 0) for spec in specs))
    result["hands"] = max(0, int(result.get("hands") or 0) + sum(int(spec.get("hands") or 0) for spec in specs))
    result["attachment_gear_modifier"] = sum(int(spec.get("gear") or 0) for spec in specs)
    result["attachment_melee_damage"] = sum(int(spec.get("melee_damage") or 0) for spec in specs)
    shift = sum(int(spec.get("range") or 0) for spec in specs)
    if result.get("use_range") in RANGE_ORDER and shift:
        index = max(0, min(len(RANGE_ORDER) - 1, RANGE_ORDER.index(result["use_range"]) + shift))
        result["use_range"] = RANGE_ORDER[index]
    return result
